# 暂时先使用该方式，后期还是要整合到starter二方包模块中
spring:
  application:
    name: dubbo-provider

dubbo:
  scan:
    base-packages: com.zjut.factory.provider.openservice.service.impl
  protocol:
    name: dubbo
    port: -1  #自行去找一个可用的端口
  registry:
    address: zookeeper://dev.cdh.ecarx.local:${embedded.zookeeper.port}
#    file: ${user.home}/dubbo-cache/${spring.application.name}/dubbo.cache
#  metadata-report:
#    address: zookeeper://127.0.0.1:2181

embedded:
  zookeeper:
    port: 2181