# 暂时先使用该方式，后期还是要整合到starter二方包模块中
spring:
  dubbo:
    application:
      name: dubbo-provider #应用名
    registry:
      address: zookeeper://dev.cdh.ecarx.local:2181 #zookeeper地址
      port: 2181 #提供注册的端口
    protocol:
      name: dubbo
      port: 20890 #dubbo服务暴露的端口
    scan: com.zjut.factory.provider.openservice.service.impl #扫描的包名
#dubbo:
#  application:
#    name: springboot-dubbo-provider
#  registry:
#    address: zookeeper://dev.cdh.ecarx.local:2181
